import '../core/money/money.dart';
// lib/services/transaction_application_service.dart

import '../models/transaction.dart';
import '../constants/transaction_constants.dart';
import 'account_service.dart';
import 'transaction_query_service.dart';
import '../financial_engine/engine/financial_operation_engine.dart';
import '../financial_engine/execution_context/execution_context.dart';
import '../financial_engine/results/operation_result.dart';

import '../financial_engine/commands/credit_card/credit_card_charge_intent.dart';
import '../financial_engine/operations/credit_card_charge_operation.dart';
import '../financial_engine/commands/expense/expense_command.dart';
import '../financial_engine/commands/expense/expense_intent.dart';
import '../financial_engine/commands/shared/transaction_metadata.dart';
import '../financial_engine/commands/expense/expense_command_mapper.dart';

import '../financial_engine/commands/income/income_command.dart';
import '../financial_engine/commands/income/income_intent.dart';
import '../financial_engine/commands/income/income_command_mapper.dart';

import '../financial_engine/commands/transfer/transfer_command.dart';
import '../financial_engine/commands/transfer/transfer_intent.dart';
import '../financial_engine/commands/transfer/transfer_command_mapper.dart';

import '../financial_engine/commands/correction/correction_command.dart';
import '../financial_engine/commands/correction/correction_intent.dart';
import '../financial_engine/commands/correction/correction_command_mapper.dart';

import '../financial_engine/adapters/transaction_record_mapper.dart';

import '../financial_engine/commands/correction/delete_transaction_command.dart';
import '../financial_engine/commands/correction/delete_transaction_command_mapper.dart';
import '../financial_engine/commands/correction/deletion_transaction_intent.dart';

/// Application Orchestrator for transaction-related operations.
/// This is the single entry point for the UI and other clients.
/// It delegates to the appropriate underlying service (Engine or Legacy).
class TransactionApplicationService {
  final FinancialOperationEngine _engine;
  final TransactionQueryService _transactionQueryService;

  TransactionApplicationService({
    required FinancialOperationEngine engine,
    required TransactionQueryService transactionQueryService,
  }) : _engine = engine,
       _transactionQueryService = transactionQueryService;

  // ==================== Credit Card Charge (via Engine) ====================

  Future<OperationResult> addCreditCardCharge({
    required String creditCardAccountId,
    required double amount,
    required String categoryId,
    required DateTime occurredAt,
    required String currencyCode,
    String? note,
    String? actorMemberId,
    String? idempotencyKey,
    bool isExceptional = false,
  }) async {
    final context = ExecutionContext(
      idempotencyKey:
          idempotencyKey ?? 'cc-${DateTime.now().microsecondsSinceEpoch}',
      actorMemberId: actorMemberId,
      source: 'manual',
      commandType: 'CreditCardCharge',
    );

    final operation = CreditCardChargeOperation(
      intent: CreditCardChargeIntent(
        creditCardAccountId: creditCardAccountId,
        categoryId: categoryId,
        amount: Money.fromDouble(amount),
        isExceptional: isExceptional,
        actorMemberId: actorMemberId,
      ),
      metadata: TransactionMetadata(
        occurredAt: occurredAt,
        paymentMethod: 'credit_card',
        currencyCode: currencyCode,
        note: note,
      ),
      context: context,
    );

    return _engine.execute(operation, context);
  }

  // ==================== Expense (via Engine) ====================

  Future<OperationResult> addExpense({
    required String sourceAccountId,
    required double amount,
    required String categoryId,
    required DateTime occurredAt,
    required bool isExceptional,
    String? actorMemberId,
    String? note,
    String? idempotencyKey,
  }) async {
    // TODO(V4):
    // Replace with durable operation id generated by the Application Layer.
    final context = ExecutionContext(
      idempotencyKey:
          idempotencyKey ?? DateTime.now().millisecondsSinceEpoch.toString(),
      actorMemberId: actorMemberId,
      source: 'manual',
      commandType: 'ExpenseCommand',
    );

    final command = ExpenseCommand(
      intent: ExpenseIntent(
        sourceAccountId: sourceAccountId,
        amount: Money.fromDouble(amount),
        categoryId: categoryId,
        isExceptional: isExceptional,
        actorMemberId: actorMemberId,
      ),
      metadata: TransactionMetadata(
        occurredAt: occurredAt,
        note: note,
        paymentMethod: 'default',
        currencyCode: 'EGP',
      ),
      context: context,
    );

    final operation = _expenseCommandMapper.map(command);

    return await _engine.execute(operation, context);
  }

  // ==================== Income (via Engine) ====================

  Future<OperationResult> addIncome({
    required String sourceAccountId,
    required double amount,
    required String categoryId,
    required DateTime occurredAt,
    required bool isExceptional,
    String? actorMemberId,
    String? note,
  }) async {
    // TODO(V4):
    // Replace with durable operation id generated by the Application Layer.
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
      actorMemberId: actorMemberId,
      source: 'manual',
      commandType: 'IncomeCommand',
    );

    final command = IncomeCommand(
      intent: IncomeIntent(
        sourceAccountId: sourceAccountId,
        amount: Money.fromDouble(amount),
        categoryId: categoryId,
        isExceptional: isExceptional,
        actorMemberId: actorMemberId,
      ),
      metadata: TransactionMetadata(
        occurredAt: occurredAt,
        note: note,
        paymentMethod: 'default',
        currencyCode: 'EGP',
      ),
      context: context,
    );

    final operation = _incomeCommandMapper.map(command);

    return await _engine.execute(operation, context);
  }
  // ====================== Transfer  (via Engine) ====================

  Future<OperationResult> addTransfer({
    required String fromAccountId,
    required String toAccountId,
    required double amount,
    required DateTime occurredAt,
    String? note,
  }) async {
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
      source: 'manual',
      commandType: 'TransferCommand',
    );

    final sourceAccount = AccountService().getById(fromAccountId);
    final currencyCode = sourceAccount?.currency ?? 'EGP';

    final command = TransferCommand(
      intent: TransferIntent(
        fromAccountId: fromAccountId,
        toAccountId: toAccountId,
        amount: Money.fromDouble(amount),
      ),
      metadata: TransactionMetadata(
        occurredAt: occurredAt,
        note: note,
        paymentMethod: 'default',
        currencyCode: currencyCode,
      ),
      context: context,
    );

    final operation = _transferCommandMapper.map(command);

    return await _engine.execute(operation, context);
  }

  // Legacy generic transaction mutation methods were intentionally removed.
  // Financial writes must enter through FinancialOperationEngine.

  // ==================== Update (Engine-based) ====================

  Future<OperationResult> updateExpense(Transaction transaction) async {
    return await _updateViaEngine(transaction);
  }

  /// Correct an existing Credit Card charge without changing its financial
  /// identity into a generic expense. The correction engine preserves the
  /// transaction id and applies the before/after delta to financial truth.
  Future<OperationResult> updateCreditCardCharge(
    Transaction transaction,
  ) async {
    if (transaction.type != TransactionType.creditCardCharge) {
      throw ArgumentError(
        'updateCreditCardCharge requires a credit_card_charge transaction.',
      );
    }
    if (transaction.toAccountId == null || transaction.toAccountId!.isEmpty) {
      throw ArgumentError(
        'A Credit Card charge must keep its liability account in toAccountId.',
      );
    }

    return await _updateViaEngine(transaction);
  }

  Future<OperationResult> updateIncome(Transaction transaction) async {
    return await _updateViaEngine(transaction);
  }

  Future<OperationResult> updateTransfer(Transaction transaction) async {
    return await _updateViaEngine(transaction);
  }

  Future<OperationResult> _updateViaEngine(Transaction transaction) async {
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
      source: 'manual',
      commandType: 'CorrectionCommand',
    );

    final beforeTransaction = _transactionQueryService.getById(transaction.id);
    if (beforeTransaction == null) {
      throw StateError('Transaction not found: ${transaction.id}');
    }

    final before = _transactionRecordMapper.fromTransaction(beforeTransaction);
    final after = _transactionRecordMapper.fromTransaction(transaction);

    final command = CorrectionCommand(
      intent: CorrectionIntent(
        transactionId: transaction.id,
        before: before,
        after: after,
      ),
      metadata: TransactionMetadata(
        occurredAt: transaction.date,
        note: transaction.note,
        paymentMethod: transaction.paymentMethod,
        currencyCode: transaction.currencyCode,
      ),
      context: context,
    );

    final operation = _correctionCommandMapper.map(command);

    return await _engine.execute(operation, context);
  }

  // ==================== Delete (Temporary Legacy Delegation) ====================

  Future<OperationResult> delete(String transactionId) async {
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
      source: 'manual',
      commandType: 'DeleteTransactionCommand',
    );

    final transaction = _transactionQueryService.getById(transactionId);

    if (transaction == null) {
      throw Exception('Transaction not found: $transactionId');
    }

    final command = DeleteTransactionCommand(
      intent: DeleteTransactionIntent(transaction: transaction),
      metadata: TransactionMetadata(
        occurredAt: transaction.date,
        note: transaction.note,
        paymentMethod: transaction.paymentMethod,
        currencyCode: transaction.currencyCode,
      ),
      context: context,
    );

    final operation = _deleteTransactionCommandMapper.map(command);

    return await _engine.execute(operation, context);
  }
  // =======================================================

  // ==================== Query methods (delegated to legacy) ====================

  List<Transaction> getAllTransactions() =>
      _transactionQueryService.getAllTransactions();

  Transaction? getById(String id) => _transactionQueryService.getById(id);

  List<Transaction> getByType(String type) =>
      _transactionQueryService.getByType(type);

  List<Transaction> getIncomeTransactions() =>
      _transactionQueryService.getIncomeTransactions();

  List<Transaction> getExpenseTransactions() =>
      _transactionQueryService.getExpenseTransactions();

  List<Transaction> getByCategory(String categoryId) =>
      _transactionQueryService.getByCategory(categoryId);

  List<Transaction> getByDateRange(DateTime start, DateTime end) =>
      _transactionQueryService.getByDateRange(start, end);

  List<Transaction> getForAccount(String accountId) =>
      _transactionQueryService.getForAccount(accountId);

  bool hasTransactionsForAccount(String accountId) =>
      _transactionQueryService.hasTransactionsForAccount(accountId);

  double getTotalByType(String type, DateTime start, DateTime end) =>
      _transactionQueryService.getTotalByType(type, start, end);

  double getTotalExpenses(DateTime start, DateTime end) =>
      _transactionQueryService.getTotalExpenses(start, end);

  double getTotalIncome(DateTime start, DateTime end) =>
      _transactionQueryService.getTotalIncome(start, end);

  double getNormalExpenses(DateTime start, DateTime end) =>
      _transactionQueryService.getNormalExpenses(start, end);

  double getExceptionalExpenses(DateTime start, DateTime end) =>
      _transactionQueryService.getExceptionalExpenses(start, end);

  Map<String, double> getExpensesByCategory(DateTime start, DateTime end) =>
      _transactionQueryService.getExpensesByCategory(start, end);

  Map<String, double> getExpensesBySource(DateTime start, DateTime end) =>
      _transactionQueryService.getExpensesBySource(start, end);

  List<Transaction> getLegacyTransactions() =>
      _transactionQueryService.getLegacyTransactions();

  int get count => _transactionQueryService.count;
  bool get isEmpty => _transactionQueryService.isEmpty;
  bool get isNotEmpty => _transactionQueryService.isNotEmpty;

  final ExpenseCommandMapper _expenseCommandMapper =
      const ExpenseCommandMapper();

  final IncomeCommandMapper _incomeCommandMapper = const IncomeCommandMapper();
  final TransferCommandMapper _transferCommandMapper =
      const TransferCommandMapper();

  final CorrectionCommandMapper _correctionCommandMapper =
      const CorrectionCommandMapper();

  final TransactionRecordMapper _transactionRecordMapper =
      const TransactionRecordMapper();

  final DeleteTransactionCommandMapper _deleteTransactionCommandMapper =
      const DeleteTransactionCommandMapper();
}
