// lib/services/transaction_application_service.dart

import '../models/transaction.dart';
import 'transaction_service.dart';
import '../financial_engine/engine/financial_operation_engine.dart';
import '../financial_engine/operations/expense_operation.dart';
import '../financial_engine/execution_context/execution_context.dart';
import '../financial_engine/results/operation_result.dart';

/// Application Orchestrator for transaction-related operations.
/// This is the single entry point for the UI and other clients.
/// It delegates to the appropriate underlying service (Engine or Legacy).
class TransactionApplicationService {
  final FinancialOperationEngine _engine;
  final TransactionService _legacyTransactionService;

  TransactionApplicationService({
    required FinancialOperationEngine engine,
    required TransactionService legacyTransactionService,
  }) : _engine = engine,
       _legacyTransactionService = legacyTransactionService;

  // ==================== Expense (via Engine) ====================

  Future<OperationResult> addExpense({
    required String sourceAccountId,
    required double amount,
    required String categoryId,
    required DateTime occurredAt,
    String? note,
  }) async {
    final operation = ExpenseOperation(
      sourceAccountId: sourceAccountId,
      amount: amount,
      categoryId: categoryId,
      occurredAt: occurredAt,
      note: note,
    );

    // TODO(V4):
    // Replace with durable operation id generated by the Application Layer.
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
    );

    return await _engine.execute(operation, context);
  }

  // ==================== Legacy operations (delegated to TransactionService) ====================

  Future<void> addTransaction(Transaction transaction) async {
    // For now, we delegate to legacy service.
    // In future, we will migrate all operations to Engine.
    await _legacyTransactionService.addTransaction(transaction);
  }

  Future<void> updateTransaction(Transaction transaction) async {
    await _legacyTransactionService.updateTransaction(transaction);
  }

  Future<void> deleteTransaction(String id) async {
    await _legacyTransactionService.deleteTransaction(id);
  }

  Future<void> deleteAllTransactions() async {
    await _legacyTransactionService.deleteAllTransactions();
  }

  // ==================== Query methods (delegated to legacy) ====================

  List<Transaction> getAllTransactions() =>
      _legacyTransactionService.getAllTransactions();

  Transaction? getById(String id) => _legacyTransactionService.getById(id);

  List<Transaction> getByType(String type) =>
      _legacyTransactionService.getByType(type);

  List<Transaction> getIncomeTransactions() =>
      _legacyTransactionService.getIncomeTransactions();

  List<Transaction> getExpenseTransactions() =>
      _legacyTransactionService.getExpenseTransactions();

  List<Transaction> getByCategory(String categoryId) =>
      _legacyTransactionService.getByCategory(categoryId);

  List<Transaction> getByDateRange(DateTime start, DateTime end) =>
      _legacyTransactionService.getByDateRange(start, end);

  List<Transaction> getForAccount(String accountId) =>
      _legacyTransactionService.getForAccount(accountId);

  bool hasTransactionsForAccount(String accountId) =>
      _legacyTransactionService.hasTransactionsForAccount(accountId);

  double getTotalByType(String type, DateTime start, DateTime end) =>
      _legacyTransactionService.getTotalByType(type, start, end);

  double getTotalExpenses(DateTime start, DateTime end) =>
      _legacyTransactionService.getTotalExpenses(start, end);

  double getTotalIncome(DateTime start, DateTime end) =>
      _legacyTransactionService.getTotalIncome(start, end);

  double getNormalExpenses(DateTime start, DateTime end) =>
      _legacyTransactionService.getNormalExpenses(start, end);

  double getExceptionalExpenses(DateTime start, DateTime end) =>
      _legacyTransactionService.getExceptionalExpenses(start, end);

  Map<String, double> getExpensesByCategory(DateTime start, DateTime end) =>
      _legacyTransactionService.getExpensesByCategory(start, end);

  Map<String, double> getExpensesBySource(DateTime start, DateTime end) =>
      _legacyTransactionService.getExpensesBySource(start, end);

  List<Transaction> getLegacyTransactions() =>
      _legacyTransactionService.getLegacyTransactions();

  int get count => _legacyTransactionService.count;
  bool get isEmpty => _legacyTransactionService.isEmpty;
  bool get isNotEmpty => _legacyTransactionService.isNotEmpty;
}
