// lib/services/transaction_application_service.dart

import '../models/transaction.dart';
import 'transaction_service.dart';
import '../financial_engine/engine/financial_operation_engine.dart';
import '../financial_engine/execution_context/execution_context.dart';
import '../financial_engine/results/operation_result.dart';

import '../financial_engine/commands/expense/expense_command.dart';
import '../financial_engine/commands/expense/expense_intent.dart';
import '../financial_engine/commands/shared/transaction_metadata.dart';
import '../financial_engine/commands/expense/expense_command_mapper.dart';

import '../financial_engine/commands/income/income_command.dart';
import '../financial_engine/commands/income/income_intent.dart';
import '../financial_engine/commands/income/income_command_mapper.dart';

import '../financial_engine/commands/transfer/transfer_command.dart';
import '../financial_engine/commands/transfer/transfer_intent.dart';
import '../financial_engine/commands/transfer/transfer_command_mapper.dart';

import '../financial_engine/commands/correction/correction_command.dart';
import '../financial_engine/commands/correction/correction_intent.dart';
import '../financial_engine/commands/correction/correction_command_mapper.dart';

import '../financial_engine/adapters/transaction_record_mapper.dart';

/// Application Orchestrator for transaction-related operations.
/// This is the single entry point for the UI and other clients.
/// It delegates to the appropriate underlying service (Engine or Legacy).
class TransactionApplicationService {
  final FinancialOperationEngine _engine;
  final TransactionService _legacyTransactionService;

  TransactionApplicationService({
    required FinancialOperationEngine engine,
    required TransactionService legacyTransactionService,
  }) : _engine = engine,
       _legacyTransactionService = legacyTransactionService;

  // ==================== Expense (via Engine) ====================

  Future<OperationResult> addExpense({
    required String sourceAccountId,
    required double amount,
    required String categoryId,
    required DateTime occurredAt,
    required bool isExceptional,
    String? actorMemberId,
    String? note,
  }) async {
    // TODO(V4):
    // Replace with durable operation id generated by the Application Layer.
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
    );

    final command = ExpenseCommand(
      intent: ExpenseIntent(
        sourceAccountId: sourceAccountId,
        amount: amount,
        categoryId: categoryId,
        isExceptional: isExceptional,
        actorMemberId: actorMemberId,
      ),
      metadata: TransactionMetadata(
        occurredAt: occurredAt,
        note: note,
        paymentMethod: 'default',
        currencyCode: 'EGP',
      ),
      context: context,
    );

    final operation = _expenseCommandMapper.map(command);

    return await _engine.execute(operation, context);
  }

  // ==================== Income (via Engine) ====================

  Future<OperationResult> addIncome({
    required String sourceAccountId,
    required double amount,
    required String categoryId,
    required DateTime occurredAt,
    required bool isExceptional,
    String? actorMemberId,
    String? note,
  }) async {
    // TODO(V4):
    // Replace with durable operation id generated by the Application Layer.
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
    );

    final command = IncomeCommand(
      intent: IncomeIntent(
        sourceAccountId: sourceAccountId,
        amount: amount,
        categoryId: categoryId,
        isExceptional: isExceptional,
        actorMemberId: actorMemberId,
      ),
      metadata: TransactionMetadata(
        occurredAt: occurredAt,
        note: note,
        paymentMethod: 'default',
        currencyCode: 'EGP',
      ),
      context: context,
    );

    final operation = _incomeCommandMapper.map(command);

    return await _engine.execute(operation, context);
  }
  // ====================== Transfer  (via Engine) ====================

  Future<OperationResult> addTransfer({
    required String fromAccountId,
    required String toAccountId,
    required double amount,
    required DateTime occurredAt,
    String? note,
  }) async {
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
    );

    final command = TransferCommand(
      intent: TransferIntent(
        fromAccountId: fromAccountId,
        toAccountId: toAccountId,
        amount: amount,
      ),
      metadata: TransactionMetadata(
        occurredAt: occurredAt,
        note: note,
        paymentMethod: 'default',
        currencyCode: 'EGP',
      ),
      context: context,
    );

    final operation = _transferCommandMapper.map(command);

    return await _engine.execute(operation, context);
  }

  // ==================== Legacy operations (delegated to TransactionService) ====================

  Future<void> addTransaction(Transaction transaction) async {
    // For now, we delegate to legacy service.
    // In future, we will migrate all operations to Engine.
    await _legacyTransactionService.addTransaction(transaction);
  }

  Future<void> updateTransaction(Transaction transaction) async {
    await _legacyTransactionService.updateTransaction(transaction);
  }

  Future<void> deleteTransaction(String id) async {
    await _legacyTransactionService.deleteTransaction(id);
  }

  Future<void> deleteAllTransactions() async {
    await _legacyTransactionService.deleteAllTransactions();
  }

  // ==================== Update (Temporary Legacy Delegation) ====================

  Future<void> updateExpense(Transaction transaction) async {
    await _updateViaEngine(transaction);
  }

  Future<void> updateIncome(Transaction transaction) async {
    await _updateViaEngine(transaction);
  }

  Future<void> updateTransfer(Transaction transaction) async {
    await _updateViaEngine(transaction);
  }

  Future<void> _updateViaEngine(Transaction transaction) async {
    final context = ExecutionContext(
      idempotencyKey: DateTime.now().millisecondsSinceEpoch.toString(),
    );

    final record = _transactionRecordMapper.fromTransaction(transaction);

    final command = CorrectionCommand(
      intent: CorrectionIntent(transactionId: transaction.id, after: record),
      metadata: TransactionMetadata(
        occurredAt: transaction.date,
        note: transaction.note,
        paymentMethod: transaction.paymentMethod,
        currencyCode: transaction.currencyCode,
      ),
      context: context,
    );

    final operation = _correctionCommandMapper.map(command);

    final result = await _engine.execute(operation, context);

    if (result is! OperationSucceeded) {
      throw StateError('Transaction update failed: $result');
    }
  }

  // ==================== Delete (Temporary Legacy Delegation) ====================

  Future<void> delete(String transactionId) async {
    await _legacyTransactionService.deleteTransaction(transactionId);
  }

  // =======================================================

  // ==================== Query methods (delegated to legacy) ====================

  List<Transaction> getAllTransactions() =>
      _legacyTransactionService.getAllTransactions();

  Transaction? getById(String id) => _legacyTransactionService.getById(id);

  List<Transaction> getByType(String type) =>
      _legacyTransactionService.getByType(type);

  List<Transaction> getIncomeTransactions() =>
      _legacyTransactionService.getIncomeTransactions();

  List<Transaction> getExpenseTransactions() =>
      _legacyTransactionService.getExpenseTransactions();

  List<Transaction> getByCategory(String categoryId) =>
      _legacyTransactionService.getByCategory(categoryId);

  List<Transaction> getByDateRange(DateTime start, DateTime end) =>
      _legacyTransactionService.getByDateRange(start, end);

  List<Transaction> getForAccount(String accountId) =>
      _legacyTransactionService.getForAccount(accountId);

  bool hasTransactionsForAccount(String accountId) =>
      _legacyTransactionService.hasTransactionsForAccount(accountId);

  double getTotalByType(String type, DateTime start, DateTime end) =>
      _legacyTransactionService.getTotalByType(type, start, end);

  double getTotalExpenses(DateTime start, DateTime end) =>
      _legacyTransactionService.getTotalExpenses(start, end);

  double getTotalIncome(DateTime start, DateTime end) =>
      _legacyTransactionService.getTotalIncome(start, end);

  double getNormalExpenses(DateTime start, DateTime end) =>
      _legacyTransactionService.getNormalExpenses(start, end);

  double getExceptionalExpenses(DateTime start, DateTime end) =>
      _legacyTransactionService.getExceptionalExpenses(start, end);

  Map<String, double> getExpensesByCategory(DateTime start, DateTime end) =>
      _legacyTransactionService.getExpensesByCategory(start, end);

  Map<String, double> getExpensesBySource(DateTime start, DateTime end) =>
      _legacyTransactionService.getExpensesBySource(start, end);

  List<Transaction> getLegacyTransactions() =>
      _legacyTransactionService.getLegacyTransactions();

  int get count => _legacyTransactionService.count;
  bool get isEmpty => _legacyTransactionService.isEmpty;
  bool get isNotEmpty => _legacyTransactionService.isNotEmpty;

  final ExpenseCommandMapper _expenseCommandMapper =
      const ExpenseCommandMapper();

  final IncomeCommandMapper _incomeCommandMapper = const IncomeCommandMapper();
  final TransferCommandMapper _transferCommandMapper =
      const TransferCommandMapper();

  final CorrectionCommandMapper _correctionCommandMapper =
      const CorrectionCommandMapper();

  final TransactionRecordMapper _transactionRecordMapper =
      const TransactionRecordMapper();
}
