enum FinancialActionType {
  expense,
  creditCardCharge,
  creditCardPayment,
  income,
  transfer,
  commitmentPayment,
  goalTransfer,
  goalSavingTransfer,
  createGoalAllocation,
  openingBalance,
  balanceReconciliation,
  correction,
  deletion,
}
